name: Gunluk Otomatik Shorts Uretici

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  video-uretim-sureci:
    runs-on: ubuntu-latest

    steps:
    - name: Kodlari Indir
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: FFmpeg Kurulumu
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Bagimliliklari Yukle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sistemi Calistir ve Videoyu Uret
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python main.py

    - name: Uretilen Videoyu Kaydet
      uses: actions/upload-artifact@v4
      with:
        name: gunluk-shorts-videosu
        path: final_shorts.mp4
